### PR TITLE
Issue 507 move test rules

### LINKED ISSUE #507: re-activate, update and move test related PMD rules
- [x] remove all references to `TEST_JAVA_REPOSITORY_KEY` and `TEST_REPOSITORY_NAME`
- [x] java/junit.xml rules are all commented out in sonar-pmd 4.0.1 release: need to check which are renamed and moved to bestpractices
- [x] add regression unit tests for failures found during testing in Sonar UI

### PR DESCRIPTION
**Pull request by stokpop**
closes #507

### CODE REVIEW

File: sonar-pmd-plugin/src/main/java/org/sonar/plugins/pmd/PmdPlugin.java [hunk 1]
```diff
@@ -23,7 +23,6 @@
 import org.sonar.api.config.PropertyDefinition;
 import org.sonar.plugins.pmd.rule.PmdKotlinRulesDefinition;
 import org.sonar.plugins.pmd.rule.PmdRulesDefinition;
-import org.sonar.plugins.pmd.rule.PmdUnitTestsRulesDefinition;
```
Comment (jborgers) [inline sonar-pmd-plugin/src/main/java/org/sonar/plugins/pmd/PmdPlugin.java:26]: hmm, this change is in my commit, too. We have overlap.
